# Generated by Django 3.2 on 2021-05-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadej jmeno zbrane.', max_length=50)),
                ('ammo', models.IntegerField(help_text='Zadej mnozstvi munice.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadej jmeno skupiny.', max_length=50)),
                ('leader', models.CharField(help_text='Zadej jmeno velitele skupiny.', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Solider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadej jmeno vojaka.', max_length=50)),
                ('age', models.IntegerField(help_text='Zadej vek vojaka')),
                ('weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='army_app.gun')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
