# Generated by Django 3.2 on 2021-05-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0002_auto_20210515_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='ammo_type',
            field=models.FloatField(default='7.62', help_text='Zadej typ munice.'),
        ),
        migrations.AddField(
            model_name='platoon',
            name='specialization',
            field=models.CharField(default='Zaloha', help_text='Zadejte specializaci skupiny.', max_length=255),
        ),
        migrations.AddField(
            model_name='solider',
            name='country',
            field=models.CharField(default='USA', help_text='Zadejte misto narozeni.', max_length=255),
        ),
        migrations.AlterField(
            model_name='platoon',
            name='country',
            field=models.CharField(default='neurceno', help_text='Zadejte misto nasazeni skupiny.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solider',
            name='activity',
            field=models.BooleanField(default='True', help_text='Je vojak prave aktivni?'),
        ),
    ]
