# Generated by Django 3.2 on 2021-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0003_auto_20210515_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='active_range',
            field=models.FloatField(default='200', help_text='Zadej aktivni dostrel.'),
        ),
        migrations.AddField(
            model_name='gun',
            name='fire_rate',
            field=models.FloatField(default='300', help_text='Zadejte kadenci zbrane.'),
        ),
        migrations.AddField(
            model_name='gun',
            name='max_range',
            field=models.FloatField(default='1000', help_text='Zadej maximalni dostrel.'),
        ),
        migrations.AddField(
            model_name='solider',
            name='date_of_birth',
            field=models.DateField(default='1991-01-01', help_text='Zadej datum narezeni'),
        ),
    ]
