# Generated by Django 3.2 on 2021-05-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0004_auto_20210516_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solider',
            name='age',
        ),
        migrations.AlterField(
            model_name='gun',
            name='active_range',
            field=models.IntegerField(default='200', help_text='Zadej aktivni dostrel.'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='ammo',
            field=models.FloatField(help_text='Zadej mnozstvi munice.'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='ammo_type',
            field=models.FloatField(default='9', help_text='Zadej typ munice.'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='fire_rate',
            field=models.IntegerField(default='300', help_text='Zadejte kadenci zbrane.'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='max_range',
            field=models.IntegerField(default='1000', help_text='Zadej maximalni dostrel.'),
        ),
    ]
