# Generated by Django 3.2 on 2021-05-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0005_auto_20210516_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gun',
            name='ammo',
            field=models.IntegerField(help_text='Zadej mnozstvi munice.'),
        ),
    ]
