# Generated by Django 3.2 on 2021-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0006_alter_gun_ammo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='link',
            field=models.CharField(default='../images/ak47.jpg', help_text='odkaz na obrazek.', max_length=255, null=True),
        ),
    ]
