# Generated by Django 3.2 on 2021-05-16 11:51

import army_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0007_gun_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadej název hodnosti.', max_length=100)),
                ('tree', models.CharField(help_text='Zadej název skupiny hodností.', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='vlož obrázek', null=True, upload_to=army_app.models.img_path_rank, verbose_name='Fotka')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='gun',
            name='link',
        ),
        migrations.RemoveField(
            model_name='solider',
            name='rank',
        ),
        migrations.AddField(
            model_name='gun',
            name='image',
            field=models.ImageField(blank=True, help_text='vlož obrázek', null=True, upload_to=army_app.models.img_path, verbose_name='Fotka'),
        ),
    ]
