# Generated by Django 3.2 on 2021-05-16 10:01

import army_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0007_gun_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gun',
            name='link',
        ),
        migrations.AddField(
            model_name='gun',
            name='image',
            field=models.ImageField(blank=True, help_text='vlož obrázek', null=True, upload_to=army_app.models.img_path, verbose_name='Fotka'),
        ),
    ]
