# Generated by Django 3.2 on 2021-05-17 06:26

import army_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0009_auto_20210516_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadej jmeno zbrane.', max_length=50)),
                ('weight', models.FloatField(help_text='váha kulky.')),
                ('bullet_diameter', models.FloatField(help_text='průměr kulky.')),
                ('bullet_lenght', models.FloatField(help_text='délka kulky.')),
                ('armor_penetration', models.FloatField(help_text='prostreleni zbroje.')),
                ('default_penetration', models.IntegerField(help_text='prostreleni tkání')),
                ('muzzle_speed', models.IntegerField(help_text='úsťová rychlost')),
                ('muzzle_energy', models.IntegerField(help_text='úsťová energie')),
                ('image', models.ImageField(blank=True, help_text='vlož obrázek náboje', null=True, upload_to=army_app.models.img_path, verbose_name='Fotka')),
                ('image_des', models.ImageField(blank=True, help_text='vlož obrázek s popisem', null=True, upload_to=army_app.models.img_path, verbose_name='Fotka popis')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='gun',
            name='ammo_type',
        ),
        migrations.AddField(
            model_name='gun',
            name='lenght',
            field=models.IntegerField(default='1', help_text='Zadej delku zbrane.'),
        ),
        migrations.AddField(
            model_name='gun',
            name='lenght_barrel',
            field=models.IntegerField(default='1', help_text='Zadej delku hlavne zbrane.'),
        ),
        migrations.AddField(
            model_name='gun',
            name='weight',
            field=models.IntegerField(default='1', help_text='Zadej vahu zbrane.'),
        ),
        migrations.AddField(
            model_name='solider',
            name='score_pushup',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='solider',
            name='score_run',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='solider',
            name='score_situp',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
