# Generated by Django 3.2 on 2021-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0010_auto_20210517_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='ammo_type',
            field=models.FloatField(help_text='Zadej mnozstvi munice.', null=True),
        ),
    ]
