# Generated by Django 3.2 on 2021-05-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0011_gun_ammo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gun',
            name='ammo_type',
            field=models.ForeignKey(default='1', on_delete=models.SET('5.56'), to='army_app.ammo'),
        ),
    ]
