# Generated by Django 3.2 on 2021-05-17 07:29

import army_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0012_alter_gun_ammo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammo',
            name='image',
            field=models.ImageField(blank=True, help_text='vlož obrázek náboje', null=True, upload_to=army_app.models.img_path_ammo, verbose_name='Fotka'),
        ),
        migrations.AlterField(
            model_name='ammo',
            name='image_des',
            field=models.ImageField(blank=True, help_text='vlož obrázek s popisem', null=True, upload_to=army_app.models.img_path_ammo, verbose_name='Fotka popis'),
        ),
    ]
