# Generated by Django 3.2 on 2021-05-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0013_auto_20210517_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammo',
            name='name',
            field=models.CharField(help_text='Zadej jmeno naboje.', max_length=50),
        ),
    ]
