# Generated by Django 3.2 on 2021-05-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0014_alter_ammo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='country',
            field=models.CharField(default='none', help_text='Zadejte misto vyroby.', max_length=50),
        ),
    ]
