# Generated by Django 3.2 on 2021-05-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0015_gun_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='ammo',
            name='gun1',
            field=models.TextField(default='Zbraň', help_text='používaná zbraň'),
        ),
        migrations.AddField(
            model_name='ammo',
            name='gun2',
            field=models.TextField(default='Zbraň', help_text='používaná zbraň'),
        ),
        migrations.AddField(
            model_name='ammo',
            name='gun3',
            field=models.TextField(default='Zbraň', help_text='používaná zbraň'),
        ),
        migrations.AddField(
            model_name='ammo',
            name='short_text',
            field=models.TextField(default='Zbraň', help_text='Krátké info'),
        ),
    ]
