# Generated by Django 3.2 on 2021-06-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0016_auto_20210518_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platoon',
            name='leader',
            field=models.ForeignKey(on_delete=models.SET(''), to='army_app.solider'),
        ),
    ]
